name: Practicing Project 01
on: push
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm i -g lint
      - name: Run test
        run: npm test
  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          version: 18
      - name: Install Dependencies
        run: npm ci
      - name: build
        run: npm run build