name: Practicing Project 01
on: push
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Install NodeJS
        uses: setup-node@v3
        with:
          version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm lint
      - name: Run test
        run: npm test
      - name: Build
  deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Install NodeJS
        uses: setup-node@v3
        with:
          version: 18
      - name: build
        run: npm build